### ISSUE TITLE
buggy

### ISSUE THREAD

**Issue by code-bye** [cracker4o/mw-warzone-bot#1]
![image](https://user-images.githubusercontent.com/44205014/90324807-b0339a80-df49-11ea-9411-d4a9845f4262.png)
the presentation of the statistics is a bit buggy

**Comment by cracker4o** [comment]
Yeah, this is still in progress. I just display the raw json that I get from the service. I am planning to make it pretty.

**Comment by codsec** [comment]
ah ok, i liked the project, so if you want help i can try to do something too :D

**Comment by cracker4o** [comment]
this should be fixed ow
